### ISSUE TITLE
OpsGenie Integration

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport-plugins#437]
Creating this issue to track interest in an OpsGenie plugin. A potential OpsGenie plugin would function similarly to the PagerDuty plugin. 

## RFD

- [x] https://github.com/gravitational/teleport/pull/22221

## Phase 1: Hosted plugin (13.1)

- [x] Users can configure OpsGenie plugin in Web UI to create incidents for access requests.
- [x] OpsGenie plugin can auto-approve access requests for requesters who are currently on-call.
- [x] OpsGenie plugin lives in Teleport repo and is a part of the `teleport` binary.

## Phase 2: Standalone plugin (TBD)

- [ ] Users can run the plugin as a self-hosted Teleport service.
- [ ] We have a Helm chart for Opsgenie plugin.

**Comment by r0mant** [comment]
@EdwardDowling Implementation plan:

 1. Create RFD.
 2. Implement basic incident creation / resolution flow. Someone sends an access request, the plugin creates an incident in OpsGenie. 
 4. Implement auto-approval flow.

Should function similar to PagerDuty plugin.
